### ISSUE TITLE
Test Open Issue1

### ISSUE THREAD

**Issue by poohkanw** [MigMikael/CPSUweb#1]
ถ้าใช้ Github อาจารย์แต่ละท่านจะติด Label อย่างไรเพื่อบอกว่าปัญหาที่พบคืออะไร ซึ่งมันอาจจะไม่สะดวก #question

**Comment by MigMikael** [comment]
ติด Label ได้ด้วยการกดที่แถบด้านข้างตรงรูปฟันเฟืองหลังคำว่า Lables ครับ  
โดย ณ ตอนนี้มี Label ให้เลือกทั้งหมด 7 label ครับ 
ได้แก่ bug, duplicate, enhancement, help wanted, invalid, question, wonfix ครับผม

ทั้งนี้ทั้งนั้น เอาตามที่อาจารย์สะดวกดีกว่าครับ ที่ผมเสนอ Github เพราะคิดว่าอาจารย์หลายๆ ท่านน่าจะมี account github กันอยู่แล้ว แต่ถ้าอาจารย์สะดวกใช้ mantis มากกว่า ผมก็ไม่ขัดข้องครับผม 👍
